#!/usr/bin/env python3
import time as t
import colors as c
import classes as cl
import hub
import load
import save
import os

logo='''
 _______  _        _______           _______ 
(  ___  )( \      (  ____ )|\     /|(  ___  )
| (   ) || (      | (    )|| )   ( || (   ) |
| (___) || |      | (____)|| (___) || (___) |
|  ___  || |      |  _____)|  ___  ||  ___  |
| (   ) || |      | (      | (   ) || (   ) |
| )   ( || (____/\| )      | )   ( || )   ( |
|/     \|(_______/|/       |/     \||/     \|
                                             
 _______           _______  _______ _________
(  ___  )|\     /|(  ____ \(  ____ \\__   __/
| (   ) || )   ( || (    \/| (    \/   ) (   
| |   | || |   | || (__    | (_____    | |   
| |   | || |   | ||  __)   (_____  )   | |  
| | /\| || |   | || (            ) |   | |   
| (_\ \ || (___) || (____/\/\____) |   | |   
(____\/_)(_______)(_______/\_______)   )_(   

                            (Ver. 0)
'''

def runGame():
    print(c.clear)
    print(c.yellow+str("Hello! And welcome to...."))
    t.sleep(1)
    print(c.random_color()+logo)
    t.sleep(1)
    print()
    print()
    newOrLoad()

def newOrLoad():
    newGameAsk=input(c.yellow+"Do you want to start a new game? Or load a save file?"+c.reset+" (1), (2) >>>"+c.violet).strip()
    if newGameAsk=="1":
        confirmNewFile=input(c.yellow+"Are you sure? Any old save file will be deleted."+c.reset+" (Y/N) >>>"+c.violet).strip().lower()
        if confirmNewFile=="y":
            os.system('rm player.json') #Deletes old save file
            os.system('touch player.json') #Creates new file
            cl.Player=cl.Starter #Sets player to be starting class
            save.save_game()
            nameAsk()
        elif confirmNewFile=="n":
            newOrLoad()
        else:
            neworload()
    elif newGameAsk=="2":
        print(c.yellow+"Okay! Here are your stats.")
        load.load_game()
        cl.show_player()
        confirmGameLoad=input(c.yellow+"Are you sure you want to load this?"+c.reset+" (Y/N) >>>"+c.violet).strip().lower()
        if confirmGameLoad=="y":
            town.hub()
        elif confirmGameLoad=="n":
            newOrLoad()
        else:
            print(c.yellow+"I don't understand... type Y for yes and N for no.")
            t.sleep(1.5)
            newOrLoad()
    else:
        print(c.yellow+"I don't understand... type 1 for a save file, and 2 for loading a game.")
        t.sleep(1.5)
        newOrLoad()

def intro():
    print(c.clear)
    print("This is the plot of your game.")
    t.sleep(1)
    print("You can make this whatever you want!")
    t.sleep(1)
    input("After this intro, you will head to your hub area. [Press enter]")
    save.save_game()
    load.load_game()
    hub.hub()

def nameAsk():
    nameQuestion=input(c.yellow+"What is your name? "+c.reset+ ">>>"+c.violet).strip().title()
    confirmName=input(c.yellow+"Oh, so your name is "+c.blue+nameQuestion+c.yellow+"?"+c.reset+"(Y/N) >>>"+c.violet).strip().lower()
    if confirmName=="y":
        cl.Player.name=nameQuestion
        input(c.yellow+"Okay "+c.blue+cl.Player.name+c.yellow+", your adventure is about to start. Press enter to start!")
        cl.Player.gold=0
        cl.Player.gold+=100
        save.save_game()
        intro()
    elif confirmName=="n":
        nameAsk()
    else:
        print(c.yellow+"I don't understand... type Y for yes and N for no.")
        t.sleep(1.5)
        nameAsk()

if __name__=='__main__':
    runGame()
